[package]
name = "raytracing-vulkan-rs"
version = "0.1.0"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2024"

[dependencies]
raytracer = { path = "../raytracer" }
scene_file = { path = "../scene_file" }
vulkan = { path = "../vulkan" }

anyhow = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
rfd = { workspace = true }
winit = { workspace = true }

